<% if @recipe.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger" role="alert">
            There were some errors:
        </div>
            <ul>
            <% @recipe.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
<% end %>

<%= form_for @recipe do |f| %>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="field<%= ' field_with_errors' if @recipe.errors[:name].any? %>">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div class="field">
        <%= f.label :description %>
        <%= f.text_field :description %>
    </div>
    <div class="field">
        <%= f.label :favorite %>
        <%= f.check_box :favorite %>
    </div>
    <div class="field">
        <%= f.label :public %>
        <%= f.check_box :public %>
    </div>
    <div class="form-group">
        <%= f.select(:category_ids, Category.all.collect {|c| [ c.name, c.id ] }, 
            { :prompt => "Select categories:"}, 
            { :multiple => true, :size => 5 }) %>
    </div>
    <div class="field">
        <%= f.submit %>
    </div>
    <div>
        <%= button_tag t('buttons.cancel'), type: "submit", name: "cancel", value: true %>
    </div>

<% end %>
